Ianfletcher314/issue34
brandnewbox/bnb_blazer pull request #36
Opened 2024-06-26 02:39 UTC by ianfletcher314

closes #34

daft until the logo part is added

2024-07-01 19:22 UTC, willtcarey requested changes

2024-07-01 19:22 UTC, willtcarey commented on app/views/blazer/_new_nav.html.erb
> +  });
Since we have a build now, let's do this as a stimulus controller

2024-07-01 19:22 UTC, willtcarey commented on app/views/blazer/_new_nav.html.erb
Let's put this inside of bnb_blazer folder and just call it `_nav` and update any references necessary

2024-07-04 20:45 UTC, willtcarey commented on Gemfile.lock
We should undo the changes on this file.We didn't wind up keeping this file

2024-07-04 20:45 UTC, willtcarey commented on app/views/blazer/queries/show.html.erb
> +</div>
This all seems like it should go above the `margin-bottom` up above?

2024-07-05 15:50 UTC, ianfletcher314 commented on app/views/blazer/queries/show.html.erb
> +</div>
I moved the content above the margin-bottom but when I do that the new card hugs the nav:
<img width="1371" alt="image" src="https://github.com/brandnewbox/bnbintel/assets/77754482/2ddcc67d-af0b-4315-a8da-1acf13a499c7">

when they content gos bellow the margin bottom the card appears as part of the main content which @vikascripps had suggested:
<img width="1432" alt="image" src="https://github.com/brandnewbox/bnbintel/assets/77754482/7a052621-8b60-4a64-870c-5c97456d7a7a">

2024-07-05 19:31 UTC, willtcarey commented on app/views/blazer/queries/show.html.erb
> +</div>
Ok, that seems fine to have it go below the bottom margin, but I still think it should be moved above the error and description sections

2024-07-05 19:32 UTC, willtcarey reviewed
See above

2024-07-05 21:20 UTC, willtcarey approved these changes

2024-07-05 21:31 UTC, merged